package rules;


import de.jonashackt.springdrools.internalmodel.EmploymentDetail;
import de.jonashackt.springdrools.internalmodel.BirthDetail;
import de.jonashackt.springdrools.internalmodel.ApplicationRuleResult;
import de.jonashackt.springdrools.internalmodel.ApplicationFeatures;


//from row number: 1
//ROW1
rule "Row 1 givenlenderagerule"
	salience 100
	dialect "mvel"
	when
		exists (appFeature3 : ApplicationFeatures( this != null , lender != null , lender == "FULLERTON" )) 
		exists (birthDetail3 : BirthDetail( this != null , age != null , age >= 21.0 , age <= 55.0 )) 
		exists (empDetail : EmploymentDetail( this != null , employementType != null , employementType == "SALARIED" )) 
		appRuleResult : ApplicationRuleResult( this != null , givenLenderAgeRuleDecision == null )
	then
	    System.out.println("Row 1 givenlenderagerule fired");
		modify( appRuleResult ) {
				setGivenLenderAgeRuleDecision( true )
		}
end

//from row number: 2
//ROW2
rule "Row 2 givenlenderagerule"
	salience 100
	dialect "mvel"
	when
		exists (appFeature3 : ApplicationFeatures( this != null , lender != null , lender == "FULLERTON" )) 
		exists (birthDetail3 : BirthDetail( this != null , age != null , age >= 25.0 , age <= 55.0 )) 
		exists (empDetail : EmploymentDetail( this != null , employementType != null , employementType == "SELF_EMP" )) 
		appRuleResult : ApplicationRuleResult( this != null , givenLenderAgeRuleDecision == null )
	then
	    System.out.println("Row 2 givenlenderagerule fired");
		modify( appRuleResult ) {
				setGivenLenderAgeRuleDecision( true )
		}
end

//from row number: 3
//ROW3
rule "Row 3 givenlenderagerule"
	salience 100
	dialect "mvel"
	when
		exists (appFeature3 : ApplicationFeatures( this != null , lender != null , lender == "IIFL" )) 
		exists (birthDetail3 : BirthDetail( this != null , age != null , age >= 21.0 , age <= 56.0 )) 
		exists (empDetail : EmploymentDetail( this != null , employementType != null , employementType == "SALARIED" )) 
		appRuleResult : ApplicationRuleResult( this != null , givenLenderAgeRuleDecision == null )
	then
	    System.out.println("Row 3 givenlenderagerule fired");
		modify( appRuleResult ) {
				setGivenLenderAgeRuleDecision( true )
		}
end

//from row number: 4
//ROW4
rule "Row 4 givenlenderagerule"
	salience 100
	dialect "mvel"
	when
		exists (appFeature3 : ApplicationFeatures( this != null , lender != null , lender == "KSF" )) 
		exists (birthDetail3 : BirthDetail( this != null , age != null , age >= 21.0 , age <= 57.0 )) 
		exists (empDetail : EmploymentDetail( this != null , employementType != null , employementType == "SALARIED" )) 
		appRuleResult : ApplicationRuleResult( this != null , givenLenderAgeRuleDecision == null )
	then
	    System.out.println("Row 4 givenlenderagerule fired");
		modify( appRuleResult ) {
				setGivenLenderAgeRuleDecision( true )
		}
end

//from row number: 5
//ROW5
rule "Row 5 givenlenderagerule"
	salience 100
	dialect "mvel"
	when
		exists (appFeature3 : ApplicationFeatures( this != null , lender != null , lender == "KSF" )) 
		exists (birthDetail3 : BirthDetail( this != null , age != null , age >= 25.0 , age <= 60.0 )) 
		exists (empDetail : EmploymentDetail( this != null , employementType != null , employementType == "SELF_EMP" )) 
		appRuleResult : ApplicationRuleResult( this != null , givenLenderAgeRuleDecision == null )
	then
	    System.out.println("Row 5 givenlenderagerule fired");
		modify( appRuleResult ) {
				setGivenLenderAgeRuleDecision( true )
		}
end

//from row number: 6
//ROW6
rule "Row 6 givenlenderagerule"
	salience 100
	dialect "mvel"
	when
		exists (appFeature3 : ApplicationFeatures( this != null , lender != null , lender == "NORTHERN_ARC" )) 
		exists (birthDetail3 : BirthDetail( this != null , age != null , age >= 21.0 , age <= 58.0 )) 
		exists (empDetail : EmploymentDetail( this != null , employementType != null , employementType == "SALARIED" )) 
		appRuleResult : ApplicationRuleResult( this != null , givenLenderAgeRuleDecision == null )
	then
	    System.out.println("Row 6 givenlenderagerule fired");
		modify( appRuleResult ) {
				setGivenLenderAgeRuleDecision( true )
		}
end

//from row number: 7
//ROW7
rule "Row 7 givenlenderagerule"
	salience 100
	dialect "mvel"
	when
		exists (appFeature3 : ApplicationFeatures( this != null , lender != null , lender == "PAYUFIN" )) 
		exists (birthDetail3 : BirthDetail( this != null , age != null , age >= 21.0 , age <= 55.0 )) 
		exists (empDetail : EmploymentDetail( this != null , employementType != null , employementType == "SALARIED" )) 
		appRuleResult : ApplicationRuleResult( this != null , givenLenderAgeRuleDecision == null )
	then
	    System.out.println("Row 7 givenlenderagerule fired");
		modify( appRuleResult ) {
				setGivenLenderAgeRuleDecision( true )
		}
end

//from row number: 8
//ROW8
rule "Row 8 givenlenderagerule"
	salience 100
	dialect "mvel"
	when
		exists (appFeature3 : ApplicationFeatures( this != null , lender != null , lender == "PAYUFIN" )) 
		exists (birthDetail3 : BirthDetail( this != null , age != null , age >= 25.0 , age <= 55.0 )) 
		exists (empDetail : EmploymentDetail( this != null , employementType != null , employementType == "SELF_EMP" )) 
		appRuleResult : ApplicationRuleResult( this != null , givenLenderAgeRuleDecision == null )
	then
	    System.out.println("Row 8 givenlenderagerule fired");
		modify( appRuleResult ) {
				setGivenLenderAgeRuleDecision( true )
		}
end

//from row number: 9
//ROW9
rule "Row 9 givenlenderagerule"
	salience 99
	dialect "mvel"
	when
		exists (birthDetail3 : BirthDetail( this != null , age != null )) 
		appRuleResult : ApplicationRuleResult( this != null , givenLenderAgeRuleDecision == null )
	then
	    System.out.println("Row 9 givenlenderagerule fired");
		modify( appRuleResult ) {
				setGivenLenderAgeRuleDecision( true )
		}
end

//from row number: 10
//ROW10
rule "Row 10 givenlenderagerule"
	salience 100
	dialect "mvel"
	when
		exists (appFeature3 : ApplicationFeatures( this != null , lender != null , lender == "IDFC" )) 
		exists (birthDetail3 : BirthDetail( this != null , age != null , age >= 23.0 , age <= 55.0 )) 
		exists (empDetail : EmploymentDetail( this != null , employementType != null , employementType == "SALARIED" )) 
		appRuleResult : ApplicationRuleResult( this != null , givenLenderAgeRuleDecision == null )
	then
	    System.out.println("Row 10 givenlenderagerule fired");
		modify( appRuleResult ) {
				setGivenLenderAgeRuleDecision( true )
		}
end

//from row number: 11
//ROW11
rule "Row 11 givenlenderagerule"
	salience 100
	dialect "mvel"
	when
		exists (appFeature3 : ApplicationFeatures( this != null , lender != null , lender == "IDFC" )) 
		exists (birthDetail3 : BirthDetail( this != null , age != null , age >= 25.0 , age <= 55.0 )) 
		exists (empDetail : EmploymentDetail( this != null , employementType != null , employementType == "SELF_EMP" )) 
		appRuleResult : ApplicationRuleResult( this != null , givenLenderAgeRuleDecision == null )
	then
	    System.out.println("Row 11 givenlenderagerule fired");
		modify( appRuleResult ) {
				setGivenLenderAgeRuleDecision( true )
		}
end

